@startuml

[frontend] -> [backend] : piece moved
[frontend] -> [backend] : board name
[frontend] <- [backend] : change board state

[backend] -> [data access] : store board
[backend] <- [data access] : load board

@enduml