@startuml

[backend] -> [frontend] : start game
[data access] <- [backend] : save board
[backend] -> [frontend] : update screen
[backend] -> [frontend] : win game
[frontend] -> [backend] : real move
[frontend] -> [backend] : save board
[frontend] -> [backend] : kill piece
[frontend] -> [backend] : set starting team
[frontend] -> [backend] : set board
[frontend] -> [backend] : restart
[frontend] -> [backend] : false move

[data access] -> [backend] : load board

@enduml